
warnings_are_errors: false

language: r

matrix:
  include:
  - os: linux
    r: release
  - os: osx
    r: release

r_github_packages:
  - flr/FLCore

sudo: false

cache: packages

notifications:
  email:
    on_success: change
    on_failure: change
    
all_branches: true

deploy:
  provider: releases
  api_key:
    secure: hyuRWAEALFCTxbCVUCBuvearIBShVng3//mrAc1R8D/HvToPFQ6LqO6rvV+kCejQiRL5DVmLX9F6PR8bQSVxrnsL4MeSTmO2hLSAAfyd3Ly46oukUMhCb35wdJZinOm7dJMzXdw2qJiNKtDTVUMmVar6PHpewmg3MXDer0JIC8Y=
  skip_cleanup: true
  file_glob: true
  file: ggplotFL_*.t*gz
  on:
    branch: master
    repo: flr/ggplotFL
    tags: true
